# Site settings
title: Nick Pachulski
description: Software Consulting
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Nick Pachulski
user_description: I am a software consultant.
user_title: Software Consultant
email: nick@pachulski.me
github_username:  pachun

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
